name: Lint
run-name: Lint

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout ${{ github.repository }}"
            uses: actions/checkout@v1
          - name: Lint bash scripts
            uses: Azbagheri/shell-linter@latest
            with:
              exclude-paths: "LICENSE"
          - name: Validate composer.json
            run: composer validate --no-check-publish --strict
